### ISSUE TITLE
some macros are not present just after sardana installation

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#395] opened 2016-12-22 11:48 UTC
After installing sardana2.1.2 in suse11 64bits, we found that some macros where not found (sar_demo for instance). Macros from module demo.py where not loaded when running the MacroServer.

We found some hints on the error by debugging with pdb in sardana/macroserver/msmacromanager.py (in method reloadMacroLib).

Finding: The installation was done in a folder that had a symbolic link to another folder. A comparison is done in msmacromanager.py, which is giving that the absolute paths are different, when in fact they should be equal. They are different because in one site of the comparison the path of the symbolic link is used, and in the other side the full original path is used.

<pre>
 98  ->             if os.path.normcase(inspect.getabsfile(macro)) !=\
 99                    os.path.normcase(abs_file):
</pre>

This happens at list with macros in demo.py module. This macros are functions. Some macros that are classes are loaded correctly. Thus it is a not 100% reproducible behavior.

Because of the issue, sar_demo macro couldn't be used after fresh installation of sardana2.1.2.

**Comment by reszelaz** [comment] 2019-09-09 14:25
This issue was only reproducible on suse11 64bits, since we migrated to Python 3 this platform is not maintaiend anymore. Closing as wontfix.

**Closed by reszelaz** 2019-09-09 14:25 UTC
