### ISSUE TITLE
Docs: MacroServer environment variables are not described

### ISSUE THREAD

**Issue by teresanunez** [sardana-org/sardana#803] opened 2018-07-04 10:54 UTC
Only Scan related Macroserver environment is described in the Sardana Documentation.
A list with some environment variables can be found in the doc-camp branch of the Sardana-followup repo.

**Comment by reszelaz** [comment] 2018-07-08 12:18
Duplicate of #229.

**Closed by reszelaz** 2018-07-08 12:18 UTC
