### ISSUE TITLE
showscan blocks h5 file

### ISSUE THREAD

**Issue by rhomspuron** [sardana-org/sardana#1074] opened 2019-03-05 16:10 UTC
After to run showscan and close it, it is not possible to run another scan:
```
Door_rhoms_1 [3]: ascanct mot29 0 1 10 0.1
Operation will be saved in /homelocal/rhoms/develop/tmp/scans/20190305/20190305.dat (Spec)
Operation will be saved in /homelocal/rhoms/develop/tmp/scans/20190305/20190305.h5 (HDF5::NXscan)
Scan #5 started at Tue Mar  5 16:57:36 2019. It will take at least 0:00:00
 #Pt No    mot29      ct29      ct30      ct31       dt   
An error occurred while running Macro 'ascanct(mot29, 0.0, 1.0, 10, 0.1, 0.0) -> 650adc34-3f5f-11e9-a35c-d89ef301e23f':
Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
```

**Comment by reszelaz** [comment] 2019-07-01 10:22
This is a duplicate of #525

**Closed** 2019-07-01 10:23 UTC
Labels: bug, duplicate
