### ISSUE TITLE
Win7 64bits - Sardana 2.4.0: spock does returns the spock prompt before than expected

### ISSUE THREAD

**Issue by mrosanes** [sardana-org/sardana#717] opened 2018-03-05 16:03 UTC
Testing Sardana 2.4.0, in Win7 64bits 

Spock returns the prompt before having finished executing the macro. This should not be the case.
Even if the prompt is returned and we try execute a new macro before the first one having finished, the second macro will wait till the first finishes before beginning its execution. The only problem is that the spock profile prompt should not be returned till the first macro has finished.

How to test in spock:
<pre>
Door_demo2_1 [1]: ct 5

Mon Mar 05 08:05:10 2018

Door_demo2_1 [2]: lsm
  ct05  =         5.0
  ct06  =        10.0
  ct07  =        15.0
  ct08  =        20.0
       Name          Type   Controller   Axis
 ---------- ------------- ------------ ------
      gap02   PseudoMotor   slitctrl02      1
      mot05         Motor    motctrl02      1
      mot06         Motor    motctrl02      2
      mot07         Motor    motctrl02      3
      mot08         Motor    motctrl02      4
   offset02   PseudoMotor   slitctrl02      2

</pre>

**Comment by reszelaz** [comment] 2018-07-26 19:52
I just tried it on Windows 10, with ipython 5.7.0 and it seems to be fixed.

**Comment by dschick** [comment] 2018-07-26 21:44
just updated to ipython 5.7.0 and nothing has changed, I think only I see now some colors in the spock promt which have not been there before.

**Comment by reszelaz** [comment] 2018-07-31 08:05
This was fixed with Taurus release 4.4 (more preciselly in https://github.com/taurus-org/taurus/pull/738).

**Comment by mrosanes** [comment] 2019-02-19 15:24
I reopen it:
- testing with sardana 2.7.0
- taurus 4.5.1

Executing in spock:
<pre>ct 5</pre>
and doing 'enter'; spock returns the prompt before finishing macro execution

**Comment by reszelaz** [comment] 2019-02-19 15:36
Could you try to increase the timeout value? Let's say to 1 s? And try it?

**Comment by reszelaz** [comment] 2020-09-08 22:56
It was not reproducible with Sardana 3 on windows.

**Closed by reszelaz** 2020-09-08 22:56 UTC
Labels: bug, windows
