### ISSUE TITLE
wrong data parameter in SpockBaseDoor.processRecordData

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#1319] opened 2020-04-03 10:00 UTC
Hi,

from time to time we has observed  the during starting session spock the following error (I 've menaged to reproduce is only one time):
```
Traceback (most recent call last):
  File "/home/jkotan/testinst/lib/python2.7/site-packages/sardana-2.5.1.8-py2.7.egg/sardana/spock/spockms.py", line 471, in processRecordData
    if data['type'] == 'function':
KeyError: 'type'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```
This error is caused because `data` parameter of the processRecordData in this case does not have `type` keyword. It only contains a stack of RecordData, e.g.
```
('', {0: <sardana.macroserver.scan.scandata.Record object at 0x7f05b007ef50>, 1: <sardana.macroserver.scan.scandata.Record object at 0x7f05b007ead0>, 2: <sardana.macroserver.scan.scandata.Record object at 0x7f05b007e550>, 3: <sardana.macroserver.scan.scandata.Record object at 0x7f05b007e090>, 4: <sardana.macroserver.scan.scandata.Record object at 0x7f05b007e0d0>, 5: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f16ad0>, 6: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f16b50>, 7: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f16950>, 8: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f16b10>, 9: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f16a10>, 10: <sardana.macroserver.scan.scandata.Record object at 0x7f05b014ec90>, 11: <sardana.macroserver.scan.scandata.Record object at 0x7f05b014ec10>, 12: <sardana.macroserver.scan.scandata.Record object at 0x7f05b014eb90>, 13: <sardana.macroserver.scan.scandata.Record object at 0x7f05b014ee50>, 14: <sardana.macroserver.scan.scandata.Record object at 0x7f05b014ed90>, 15: <sardana.macroserver.scan.scandata.Record object at 0x7f05b014ee90>, 16: <sardana.macroserver.scan.scandata.Record object at 0x7f05b014edd0>, 17: <sardana.macroserver.scan.scandata.Record object at 0x7f05b014ef50>, 18: <sardana.macroserver.scan.scandata.Record object at 0x7f05b014ee10>, 19: <sardana.macroserver.scan.scandata.Record object at 0x7f05b014ed10>, 20: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1dc90>, 21: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1d790>, 22: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1d7d0>, 23: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1d650>, 24: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1d890>, 25: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1d8d0>, 26: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1d5d0>, 27: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1d590>, 28: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1d610>, 29: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1d810>, 30: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1d550>, 31: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1d850>, 32: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e1d910>, 33: <sardana.macroserver.scan.scandata.Record object at 0x7f05b01602d0>, 34: <sardana.macroserver.scan.scandata.Record object at 0x7f05b0160bd0>, 35: <sardana.macroserver.scan.scandata.Record object at 0x7f05b0160410>, 36: <sardana.macroserver.scan.scandata.Record object at 0x7f05b0160590>, 37: <sardana.macroserver.scan.scandata.Record object at 0x7f05b0160550>, 38: <sardana.macroserver.scan.scandata.Record object at 0x7f05b0160450>, 39: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4ae50>, 40: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4ae10>, 41: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4ad10>, 42: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4ad90>, 43: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4acd0>, 44: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a810>, 45: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4ab10>, 46: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a490>, 47: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a890>, 48: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a750>, 49: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a090>, 50: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a450>, 51: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a250>, 52: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a210>, 53: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a150>, 54: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a0d0>, 55: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a310>, 56: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a2d0>, 57: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a3d0>, 58: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a190>, 59: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4a790>, 60: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1f4aa50>, 61: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d790>, 62: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d590>, 63: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d810>, 64: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d750>, 65: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8db10>, 66: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8de50>, 67: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d390>, 68: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8de10>, 69: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d5d0>, 70: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d450>, 71: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8db50>, 72: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d190>, 73: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d490>, 74: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d3d0>, 75: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d410>, 76: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d1d0>, 77: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d250>, 78: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d290>, 79: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8db90>, 80: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d350>, 81: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d090>, 82: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d210>, 83: <sardana.macroserver.scan.scandata.Record object at 0x7f05a1e8d050>, 84: <sardana.macroserver.scan.scandata.Record object at 0x7f058c89ba50>, 85: <sardana.macroserver.scan.scandata.Record object at 0x7f058c89ba10>, 86: <sardana.macroserver.scan.scandata.Record object at 0x7f058c89b9d0>, 87: <sardana.macroserver.scan.scandata.Record object at 0x7f058c89b990>, 88: <sardana.macroserver.scan.scandata.Record object at 0x7f058c89b950>, 89: <sardana.macroserver.scan.scandata.Record object at 0x7f058c89b910>, 90: <sardana.macroserver.scan.scandata.Record object at 0x7f05b00c1710>, 91: <sardana.macroserver.scan.scandata.Record object at 0x7f05b00c1690>, 92: <sardana.macroserver.scan.scandata.Record object at 0x7f05b00c1cd0>, 93: <sardana.macroserver.scan.scandata.Record object at 0x7f05b00c1c50>, 94: <sardana.macroserver.scan.scandata.Record object at 0x7f05b00c19d0>, 95: <sardana.macroserver.scan.scandata.Record object at 0x7f05b00c1bd0>, 96: <sardana.macroserver.scan.scandata.Record object at 0x7f05b00c18d0>, 97: <sardana.macroserver.scan.scandata.Record object at 0x7f05b00c1dd0>, 98: <sardana.macroserver.scan.scandata.Record object at 0x7f05b00c1f10>, 99: <sardana.macroserver.scan.scandata.Record object at 0x7f05b00c1a90>, 100: <sardana.macroserver.scan.scandata.Record object at 0x7f05b00c1510>})
```
emited from `QDoor.recordDataReceived(self, s, t, v)`.

To make work around it is enough to put an additional check in  `SpockBaseDoor.processRecordData` which checks if `type` keyword exists.

Zibi, do you know if this bug was fixed in later versions (currently we use 2.5.1 with some additional patches)?

**Comment by jkotan** [comment] 2020-04-15 10:38
To be more precise the parameter of `SpockBaseDoor.processRecordData` is a value of `RecordData` attribute. Its listener is added in the constructor of `BaseDoor` which triggers execution of `processRecordData`. 
I do not see to much related changes in the newest version of sardana so the problem should still exist there as well.

**Comment by reszelaz** [comment] 2020-04-15 16:31
Hi Jan, Thanks for creating the issue and for the PR already!

As you also figured out I think it is not fixed in the develop branch. Also I do not remember seeing it at ALBA but will now ask my colleagues if they have seen this error before.

Is it ok to wait with this a couple of weeks? I will be back at awork on 27.04. I'm not very familiar with this part of the code and would like to review it better.

**Comment by jkotan** [comment] 2020-04-16 07:12
Hi Zibi. Thanks. Take your time. Indeed, it would be good to look at the code if its logic is correct.

**Comment by tiagocoutinho** [comment] 2020-04-16 07:18
I cannot reproduce this.
I agree that the client that handles record data event should be robust to handle any kind of record data events.
So far the client was assuming a "well behaved" record data but nothing prevents a user from writing a macro which produces other kinds of record data. In this case spock should simply ignore them.
Your PR is much appreciated.

**Comment by jkotan** [comment] 2020-04-16 07:32
I agree. It's really hard to reproduce it. I've managed to do with to sessions of spock, where before running second session I've starter a scan in the first session.   An also then it most often works without problems, it looks like it is some timing/event issue.

**Comment by jkotan** [comment] 2020-04-17 09:27
BTW, do you know if DataRecord is always a dictionary or it can be something else e.g. a list. If it can be something else one has to add to the PR a check if it is a `dict`

**Comment by reszelaz** [comment] 2020-05-04 23:34
Hi Jan,

Thanks for waiting!
I reviewed the code and below I summerize how it works now.

In the core layer:
* `Door.record_data` property which setter fires the Sardana event
* `MacroExecutor.sendRecordData()` which sets the`Door.record_data` property
* `Macro.sendRecordData()` which calls the `MacroExecutor.sendRecordData()`
* `JSONRecorder` which basically calls the `Macro.sendRecordData()`

In the Tango server layer:
* `RecordData` (`DevEncoded`) attribute which:
    * when read will return the value stored in the`Macro.data` property
    * push events with value passed as argument of `Macro.sendRecordData()`
* `matplotlib.pylab` plotting handler which reuses the `RecordData` attribute to push events with the plotting calls to the client
* `matplotlib.pyplot` plotting handler which reuses the `RecordData` attribute to push events with the plotting calls to the client

In Spock:
* magic command `macrodata` which reads `RecordData` Tango attribute
* magic command `showscan online` (also applies to online scan plots in the TaurusGUI) uses`DynamicPlotManager.onRecordDataUpdated()` slot connected to `recordDataUpdated` signal)

In the Sardana-Taurus extension (Tango client layer):
* `BaseDoor` which basically inherits from `taurus.TangoDevice` and implements:
    * `recordDataReceived()` - listener to RecordData atribute events which:
        * ignores non change/periodic events
        * calls `BaseDoor._processRecordData()`
    * `_processRecordData()` which actually decodes the data
    * `processRecordData()` which does nothing (`pass`)
* `SpockBaseDoor` which inherits from `BaseDoor` and implements:
    * `_processRecordData()` which:
        * warns about big `RecordData` value
        * calls the super class `BaseDoor._processRecordData()`
    * `processRecordData()` which calls the `matplotplib.pyplot` or `matplotlib.pylab` functions received in the event value
* `SpockDoor` which inherits from `SpockBaseDoor` and implements:
    * [**A**]`_processRecordData()` which:
        * calls the super class `SpockBaseDoor._processRecordData()`
        * calls the super class `SpockBaseDoor.processRecordData()`
* `QSpockDoor` which inherits from `SpockBaseDoor` which:
    *  in its constructor:
        *  calls the super class `SpockBaseDoor` constructor
        *  connects the super class `SpockBaseDoor.processRecordData()` slot to the `recordDataUpdated` signal
    * [**B**] implments `recordDataReceived()` which checks the `pylab` mode if it is `inline` then it calls the super class `BaseDoor.recordDataReceived` and then call super class `SpockBaseDoor.processRecordData()`.
* `QDoor` which inherits from `BaseDoor` and:
    * implements `recordDataReceived()` which:
        * calls super class `BaseDoor.recordDataReceived()`
        * emits `recordDataUpdated` signal

I imagine the following possibilities that would explain your error:
* You somehow change the `gui_mode` in Spock to non `qt`. Then you would trigger call of [**A**]
* You use `inline` pylab mode. I think this is only possible in `jupyter qtconsole` or `jupyter notebook` but not in `ipython` (terminal). Then you would trigger call of [**B**].
* You are in a very unlucky situation... Let me explain. You use Sardana [2.5](https://github.com/sardana-org/sardana/blob/develop/CHANGELOG.md#250-2018-08-10) which corresponds Jul18 milestone. The corresponding Taurur release [4.4](https://github.com/taurus-org/taurus/blob/develop/CHANGELOG.md#440---2018-07-26) changed the serialization mode to `Serial`. This means that the Taurus listeners are no more handled by the Tango event consumer thread but in a Taurus single worker thread. This situation triggers a race condition in the `QSpockDoor` constructor. The `BaseDoor.recordDataReceived` listener handling the subscription call to `push_event` (that's why you see the list of `RecordData` objects as the event value - these are the macro data of the previous scan) added in the constructor of the `BaseDoor` may be called after we connect the `QDoor.recordDataUpdated` singal to the `SpockBaseDoor.processRecordData`.

I really doubt that you end up in [**A**] or [**B**] so you must fall into this very unlucky combination. Could you check the Taurus version that you use? The next Taurus release (4.5) revert this change and introduces backwards compatible serialization mode called `TangoSerial`.

**Comment by jkotan** [comment] 2020-05-05 05:57
Hi Zibi, thanks. Indeed, we are using Taurus 4.4 and sardana 2.5

**Comment by reszelaz** [comment] 2020-05-05 08:45
Good, then we have an explanation to your error.
If you don't consider upgrade of Taurus I would recommend that you change the [`tauruscustomsettings.TANGO_SERIALIZATION_MODE`](http://taurus-scada.org/devel/tauruscustomsettings.html#taurus.tauruscustomsettings.TANGO_SERIALIZATION_MODE) to `TangoSerial`. I fear that there are other places in Sardana that assume that the events will be processes in the event consumer thread. And I think we also suffered them at ALBA - that's why the next Taurus version reverted the change.

All the `RecordData` attribute code is very complidated, I think too much. This is because we reuse the same attribute for different purposes:
1. publish scan records from the `JSONRecorder`
2. pass plotting requests from the macro `Macro.pyplot` and `Macro.pylab` APIs
3. open the Macro API to the user to pass any arbitrary information via this attribute: `Macro.sendRecordData`

Anyway I would not refactor this now and just ensure that the point 3 works. The original problem that you report should not happen anymore with the `TangoSerial` serialization mode (Taurus >= 4.5). So, I'm closing this issue and will continue this on the PR that you proposed.

**Closed** 2020-05-05 08:49 UTC
