### ISSUE TITLE
spock does not stop/abort on Ctrl+C under Windows

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#725] opened 2018-03-28 11:04 UTC
Only in the windows installation of Sardana (2.4) spock does not react on Ctrl+C commands during a scan or a motor movement.
I tested this in different terminals such as cmd, cmder, powershell

**Comment by reszelaz** [comment] 2018-03-28 11:11
Most probably the _root cause_ is in https://github.com/sardana-org/sardana/issues/717. I suspect it has to do with some changes in the magic command's API in the recet IPython versions. I will try to get if fixed..

**Comment by reszelaz** [comment] 2018-07-26 19:52
I just tried it on Windows 10, with ipython 5.7.0 and it seems to be fixed.
Which version of Windows and ipython were you using?

**Comment by dschick** [comment] 2018-07-26 21:45
still not Ctrl-C working in a scan of sar-demo with ipython 5.7.0
Are there any other dependencies to check?
I am using Winpython as distro on Win10

**Comment by reszelaz** [comment] 2018-07-26 22:06
Tomorrow I will pass you the exact list of packages.
Actually I was suspecting that it had to do with ipython version.

**Comment by dschick** [comment] 2018-07-26 22:08
yeah sure, would have been nice, if it was so easy.
Could you reproduce the issues before the upgrade to 5.7.0?

**Comment by reszelaz** [comment] 2018-07-26 22:22
I just created a new VM and provisioned it from scratch. Before I was using Windows 7.
Are you familiar with Vagrant? I could directly pass you the Vagrantfile.

**Comment by dschick** [comment] 2018-07-27 06:44
sorry, no experience with Vagrant so far.
I have tested the behaviour on a Win10 and Win7 machine. The Win7 machine is now Linux Mint and in production. The Win10 is only for testing

**Comment by reszelaz** [comment] 2018-07-27 16:48
I use the same installation recipie as described https://github.com/sardana-org/sardana/issues/724#issuecomment-376810492.

Sources for the packages installed manually:
* Python(x,y)-2.7.10.0 - can be downloaded from [here](http://ftp.ntua.gr/pub/devel/pythonxy/Python(x,y)-2.7.10.0.exe)
* PyTango-9.2.1 - can be downloaded from [here](https://pypi.python.org/packages/fe/6e/8780412c9b04ba49177032b792e35c0461c1da49b3e204badf817bba23ec/pytango-9.2.1.Win32-py2.7.msi#md5=668c63b09c058225ad377a2ab75f43ee)

The rest comes from pip and now gives the following list:

```
C:\Users\IEUser>pip list
Package                            Version
---------------------------------- ------------
-curses                            2.2
alabaster                          0.7.6
alembic                            0.7.6
astroid                            1.3.6
astropy                            1.0.3
Babel                              1.3
backports.datetime-timestamp       1.0.2.dev0
backports.functools-lru-cache      1.0.2.dev0
backports.method-request           1.0.1.dev0
backports.shutil-get-terminal-size 1.0.0
backports.ssl-match-hostname       3.4.0.2
Beaker                             1.7.0
BeautifulSoup                      3.2.1
beautifulsoup4                     4.3.2
bleach                             2.1.3
blinker                            1.4.dev0
blosc                              1.2.7
bloscpack                          0.7.2
Bottleneck                         1.0.0
CacheControl                       0.11.5
cchardet                           0.3.5
cdecimal                           2.3
certifi                            2015.4.28
cffi                               1.1.2
chardet                            2.3.0
cloudpickle                        0.5.3
colorama                           0.3.3
configobj                          5.0.6+xy.1
configparser                       3.5.0
cov-core                           1.15.0
coverage                           3.7.1
cryptography                       1.0.dev1
cssselect                          0.9.1
cx-Freeze                          4.3.4
cyordereddict                      0.2.3.dev7
Cython                             0.27.3
datrie                             0.7.1.dev37
decorator                          3.4.2
distlib                            0.2.0
docutils                           0.12
ecdsa                              0.13.1.dev0
ed25519ll                          0.6
entrypoints                        0.2.3
enum34                             1.0.4
faulthandler                       2.4
formlayout                         1.0.15
funcsigs                           0.4
functools32                        3.2.3.post2
futures                            3.0.3
gevent                             1.0.2
gevent-websocket                   0.9.5
greenlet                           0.4.7
grin                               1.2.1+xy1
guidata                            1.7.6
guiqwt                             3.0.3
h5py                               2.5.0
html5lib                           1.0.1
idna                               2.1.dev1
ipaddress                          1.0.7
ipdb                               0.8.1
ipdbplugin                         1.4.2
ipykernel                          4.8.2
ipython                            5.7.0
ipython-genutils                   0.2.0
itango                             0.1.6
jaraco.apt                         1.0
jaraco.classes                     1.2
jaraco.collections                 1.1
jaraco.context                     1.3
jaraco.functools                   1.3
jaraco.structures                  1.0
jaraco.text                        1.4
jaraco.ui                          1.3.1
jaraco.windows                     3.4
jedi                               0.9.0
Jinja2                             2.7.3
jsonschema                         2.6.0
jupyter-client                     5.2.3
jupyter-core                       4.4.0
keyring                            5.3
libnacl                            1.4.3
linecache2                         1.0.0
lockfile                           0.10.2.post7
logilab-common                     0.63.2
lxml                               3.4.4
mahotas                            1.3.0
Mako                               1.0.1
MarkupSafe                         0.23
matplotlib                         1.4.3
mistune                            0.8.3
mock                               1.0.1
modernize                          0.4
more-itertools                     2.3.dev0
nbconvert                          5.3.1
nbformat                           4.4.0
ndg-httpsclient                    0.4.0
netifaces                          0.10.4
nose                               1.3.7
nose-cov                           1.6
nose-fixes                         1.3
numexpr                            2.4.3
numpy                              1.14.1
numpydoc                           0.6.dev0
oauthlib                           0.7.3.dev0
objgraph                           2.0.1.dev0
packaging                          15.2
pandas                             0.16.2
pandocfilters                      1.4.2
paramiko                           1.15.2
pathlib                            1.0.1
pathlib2                           2.3.2
patsy                              0.3.0
pep8                               1.6.2
pickleshare                        0.7.4
Pillow                             5.0.0
Pint                               0.8.1
pip                                18.0
ply                                3.6
prompt-toolkit                     1.0.15
psutil                             3.0.1
py                                 1.4.30
py2exe                             0.6.9
pyasn1                             0.1.8
pyasn1-modules                     0.0.6
PyAudio                            0.2.8
pycodestyle                        2.4.0
pycparser                          2.14
pycrypto                           2.6.1
pyemf                              2.0.0
pyflakes                           0.9.2
Pygments                           2.0.2
PyICU                              1.9.2+xy.1
PyJWT                              1.3.1.dev2
pylint                             1.4.3
pyMinuit                           1.2.1
PyOpenGL                           3.1.0
PyOpenGL-accelerate                3.1.0
pyOpenSSL                          0.15.1
pyparsing                          2.0.3
PyQt4                              4.11.3
pyreadline                         2.0.6+xy.1
PyStemmer                          1.3.0
pytango                            9.2.1
python-dateutil                    2.4.2
PythonQwt                          0.5.5
pytz                               2015.4
pywin                              0.3.1
pywin32                            219
PyYAML                             3.11
pyzmq                              14.7.0
QtAwesome                          0.4.4
qtconsole                          4.3.1
QtPy                               1.3.1
reportlab                          3.2.0
requests                           2.7.0
requests-oauthlib                  0.5.0
rope                               0.10.7
sampy                              1.2.1
scandir                            1.1.1.dev7
scipy                              1.0.0
scp                                0.10.2
setuptools                         40.0.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.9.0
snowballstemmer                    1.2.1.dev1
Sphinx                             1.3.2
sphinx-rtd-theme                   0.1.8
sphinxcontrib-plantuml             0.6
spyder                             3.2.7
SQLAlchemy                         1.0.6
statsmodels                        0.6.1
tables                             3.2.0
Tempita                            0.5.2
testpath                           0.3.1
tornado                            4.2
traceback2                         1.4.0
traitlets                          4.3.2
ujson                              1.33
unittest2                          1.0.1
urllib3                            1.10.4
veusz                              1.23.1
virtualenv                         13.0.3
virtualenvwrapper-win              1.2.1
ViTables                           2.2a1
wcwidth                            0.1.7
webencodings                       0.5.1
wheel                              0.24.0
Whoosh                             2.7.0
win-unicode-console                0.5
wincertstore                       0.2
wsaccel                            0.6.2
wxPython                           2.8.12.1
wxPython-common                    2.8.12.1
yappi                              0.94
yg.lockfile                        2.0
zc.lockfile                        1.1.0
```

**Comment by dschick** [comment] 2018-07-27 21:32
uff, I guess I need some time to check all these dependencies. However, I remeber that I also used PythonXY and had the same issues as now.

one issue that I might have noticed in between the lines some time ago: I cannot start Sardana with the Sardana.exe command - I get a python crash. I had/have this problem on the Win10 and Win7 with the stable and develop branch of Sardana.
I have to use the Pool.exe and MacroServer.exe to create a working session.
Could this be realted to the issue with the spock CLI? Is the MacroServer somehow responding differently?

**Comment by reszelaz** [comment] 2018-07-27 22:50
I guess that the problem you describe with the Sardana server must be related to https://github.com/tango-controls/TangoTickets/issues/7 and more precisely to the MacroServe subscription to the Pool's Element attribute. I have not tried it on Windows but it may be problematic in some combinations of dependencies... but let's come back to Spock...

I think that the problem of Spock from this issue is not related to that. As well as you, I use separate servers for Pool and MacroServer and on Win 10 now everything works well.

In the past I was able to reproduce this problem on the Win 7 env. I will try to recreate it during the next week.

Now thinking, it may have something to do with the Tango event system. I use a Tango database on the host OS (Linux). On the guest Win 10 I set the TANGO_HOST environment variable. If I'm not mistaken this time I used the FQDN address and previously I was using PQDN address.
How do you use the Tango Database on Windows?

**Comment by dschick** [comment] 2018-07-29 21:43
Hej @reszelaz I just changed the `TANGO_HOST `from PQDN to FQDN (just adding a `.localdomain` to the hostname of the virtual machine.
Aborting the scans then worked partially - it seems, that it wors once for every kind of scan macro. As soon as I once aborted a scan, I cannot abort it a second time. But when I change from e.g. an initial `ascan `to `dscan `I can again abort the `dscan `once but not twice ...

**Comment by reszelaz** [comment] 2018-07-30 15:44
Thanks! Your resultas looks strange. We will need to investigate them...

I have just tried on my new win10 environment to use PQDN TANGO_HOST but again everything works well.

Now I will proceed to recreate the environment with win7 that previously was failing for me. Let's see if I can reproduce it again.

**Comment by reszelaz** [comment] 2018-07-30 17:31
I have recreated from scratch the environment that was used used when #717 was discovered and now I can **not** reproduce the problem anymore. I have [recorded the current behavior](https://drive.google.com/uc?authuser=0&id=1jzaTqrEc9nuDTKtB19vlM3Lvp_TDscrd&export=download).

It is strange to me, but the only explanations that I see possible are:
1. sardana/taurus changed and this bug was fixed in one of the last half a year commits
2. some dependencies that were installed at that time and are installed now changed and the problem got fixed
3. the environment that we were using, and @dschick is using now, was/is somehow broken

Or maybe I'm missing something?

Regarding the point 1, @dschick when trying it now were you using the latest sardana and taurus from develop?
If yes, then we would need to check point 2 and 3.
@dschick in this case I think that the easiest would be to recreate the environment from scratch. What do you think?

Maybe the last thing, when you run Pool and MacroServer could you please run them with --log-level=debug option and monitor the logs? In case you see something strange just attach the log files here.

Many thanks again and sorry for this painful debugging!

**Comment by dschick** [comment] 2018-07-30 22:41
Hej @reszelaz 

so I was already using the latest develop branch of Sardana on the Win10 machine.
Just did another pull of the upstream and tested - it was again not working.

Then I updated taurus from 4.31 to 4.4 via pip and - voila - now Ctrl-C seems to work.

BTW: I was always testing with sar_demo if this miht be of interest too

**Comment by reszelaz** [comment] 2018-07-31 08:02
Great! I was checking different commits of Taurus and found that https://github.com/taurus-org/taurus/pull/738 fixed this issue. We will then bump the taurus requirement >= 4.4 and I think we can close this issue.

**Closed by reszelaz** 2018-07-31 08:02 UTC

**Comment by reszelaz** [comment] 2018-08-08 16:14
When doing #902 I came across this issue again. Finally it looks like a bug in spock. Or better said, spock is too optimistic and assumes that events arrive in less then 100 ms, see:
https://github.com/sardana-org/sardana/blob/06750a7feafa4dc1fcbcbb69865bc454cfa4c280/src/sardana/taurus/core/tango/sardana/macroserver.py#L302
and
https://github.com/sardana-org/sardana/blob/06750a7feafa4dc1fcbcbb69865bc454cfa4c280/src/sardana/taurus/core/tango/sardana/macroserver.py#L554

The taurus-org/taurus#738 indeed changed the events handling in taurus and could affect the behavior. This also explains aleatory behaviors observed by @dschick in https://github.com/sardana-org/sardana/issues/725#issuecomment-408708098. Also this explains why on some VM it was working and on the others not.

I've tried to increase the value to 300 ms and it worked well. I will propose a PR that should be included in Jul18.
