### ISSUE TITLE
problems in communication to sardana from python3 tango device

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#981] opened 2018-11-14 19:08 UTC
Hi,

I've just tried to set sardana environment variables (running in python2) from python3 tango device via the `pickle` `Environment` attribute (with protocol=2). A natural way to do it would be 
1) read the `Environment` attribute and load the pickle variable
2) change  environment variables in the dictionary
3) dump the dictionary to pickle back and write back to the  `Environment` attribute

Unfortunately, as a result I get the following error:
```
DevFailed: DevFailed[
DevError[
    desc = TypeError: String or Integer object expected for key, unicode found
           
  origin =   File "/home/jkotan/testinst/lib/python2.7/site-packages/sardana-2.5.1.4-py2.7.egg/sardana/tango/macroserver/MacroServer.py", line 321, in write_Environment
    self.macro_server.change_env(data)
  File "/home/jkotan/testinst/lib/python2.7/site-packages/sardana-2.5.1.4-py2.7.egg/sardana/macroserver/macroserver.py", line 691, in change_env
    env_man.setEnvObj(new_change_env)
  File "/home/jkotan/testinst/lib/python2.7/site-packages/sardana-2.5.1.4-py2.7.egg/sardana/macroserver/msenvmanager.py", line 464, in setEnvObj
    self._setOneEnv(k, v)
  File "/home/jkotan/testinst/lib/python2.7/site-packages/sardana-2.5.1.4-py2.7.egg/sardana/macroserver/msenvmanager.py", line 425, in _setOneEnv
    self._env[key] = value
  File "/usr/lib/python2.7/shelve.py", line 133, in __setitem__
    self.dict[key] = f.getvalue()
  File "/usr/lib/python2.7/bsddb/__init__.py", line 279, in __setitem__
    _DeadlockWrap(wrapF)  # self.db[key] = value
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 278, in wrapF
    self.db[key] = value

  reason = PyDs_PythonError
severity = ERR]
```
for names of env variables. It is because there are converted from `bytes` to `unicode`
(it is probably because pickle.loads() maps  a py2 `str`(=`bytes`) to a py3 `str` (=`unicode`)).

Therefore, I would like to ask what is a desire treatment in this case?
1) shall I decode all dictionary keys of Environment to byte code?
2) or shall I decode all unicode strings of Environment to byte code?
3) or unicode keys should be allowed by sardana (also for future py3 compatibility)?

In principle the following hack causes that the error disappears.
```patch
--- a/src/sardana/macroserver/msenvmanager.py
+++ b/src/sardana/macroserver/msenvmanager.py
@@ -422,10 +422,16 @@ class EnvironmentManager(MacroServerManager):
         return d, key
 
     def _setOneEnv(self, key, value):
-        self._env[key] = value
-        self._env.sync()
-        d, key = self._getCacheForKey(key)
-        d[key] = value
+        if isinstance(key, unicode):
+            self._env[str(key)] = value
+            self._env.sync()
+            d, key = self._getCacheForKey(str(key))
+            d[str(key)] = value
+        else:
+            self._env[key] = value
+            self._env.sync()
+            d, key = self._getCacheForKey(key)
+            d[key] = value
 
     def _unsetOneEnv(self, key):
         if key not in self._env:
```
Note, that in order  to reproduce the problem you have to use pytango from develop branch (v9.2.5).
(https://github.com/tango-controls/pytango/issues/213 , https://github.com/tango-controls/pytango/issues/216). Otherwise you get other errors.

**Comment by reszelaz** [comment] 2018-11-15 11:49
Thanks for the report @jkotan!

I've not tested it with Sardana with the said PyTango branch. Just made some dummy tests.
The problem seems to come from the `shelve` module implementation.

I vote for option 3. And I think that the patch could be even reduced to:
```python
if isinstance(key, unicode):
    key = str(key)
self._env[key] = value
self._env.sync()
d, key = self._getCacheForKey(key)
d[key] = value
```
Maybe @cpascual could comment since he has vast more experience with Python3 then me.

**Comment by cpascual** [comment] 2018-11-15 14:11
IMHO,  the solution should definitely be py3-friendly (taurus is already starting its py3 support and sardana will come next). 

I am afraid that the solution proposed by @reszelaz  would look bad when we apply futurize to the code (and I am even not sure how safe it is to use pickle to pass data **between python versions**). See this:

https://eev.ee/blog/2016/07/31/python-faq-how-do-i-port-to-python-3/#pickle

Note from the above link that using pickle is discouraged. They actually propose to replace it with [camel](https://eev.ee/release/2015/10/15/dont-use-pickle-use-camel/)... personally, I think that if pickle is used in this case just to serialize a dict with standard types involved  (that is the case, right?), maybe we could be better off replacing pickle with json.

**Comment by jkotan** [comment] 2018-11-15 14:40
I agree JSON is more flexible (also for c++). But then it would mean probably Sardana 3. 

How about `Door.RecordData` ? It is of `bz2_pickle`.

**Comment by reszelaz** [comment] 2018-11-15 17:54
> I am afraid that the solution proposed by @reszelaz would look bad when we apply futurize to the code 

How can we easlity check it?

> I agree JSON is more flexible (also for c++). But then it would mean probably Sardana 3.

I would leave this kind of changes for the future. AFAIK up to now pickle did not give us problems.
So, I would look for a workaround that works for the @jkotan needs.

 
> How about Door.RecordData ? It is of bz2_pickle.

AFAIK you never are going to write it, so the the workflow "read, modify and write" does not apply here.

**Comment by cpascual** [comment] 2018-11-16 08:45
> I agree JSON is more flexible (also for c++). But then it would mean probably Sardana 3.

That's a problem, yes. But maybe we can work around it by leaving both implementations and allowing to select based on a `sardanacustomsettings` entry. Then I would make the old one deprecated and use the new one as default. Then on sardana3 one could remove the old one.

 > > I am afraid that the solution proposed by @reszelaz would look bad when we apply futurize to the code

> How can we easlity check it?

This is how it looks when using futurize to provide py2+3 compatibility:
```python
from builtins import str
 
if isinstance(key, str):
    key = str(key)
self._env[key] = value
self._env.sync()
d, key = self._getCacheForKey(key)
d[key] = value
```

>> How about Door.RecordData ? It is of bz2_pickle. 

> AFAIK you never are going to write it, so the the workflow "read, modify and write" does not apply here.

Even so, I think that the concerns about pickle issues with py2+3 may still apply, don't they?

**Comment by jkotan** [comment] 2018-11-16 09:18
Is the ticket closed ?

**Comment by jkotan** [comment] 2018-11-16 09:53
@cpascual, your futurized  version cannot be like above because it does not work (it is not enough the code looks nice). 
You get from a `pickle`  a key as a `bytes` or `unicode`( = `str` for py3) so if you introduce a new type from `builtins` you cannot compare it to anything. You have relation between the types many-to-one
(`unicode`, `str` (virtual because of py2 and py3 relation) , `bytes` ) to (`builtins.str`) and logically mapping cannot work in both directions (only in limited cases).

So for me if you use `pickle` you cannot use `builtins.str` (do we have to?).

**Comment by cpascual** [comment] 2018-11-16 14:12
>@cpascual, your futurized version cannot be like above because it does not work (it is not enough the code looks nice).
You get from a pickle a key as a bytes or unicode( = str for py3) so if you introduce a new type from builtins you cannot compare it to anything. You have relation between the types many-to-one
(unicode, str (virtual because of py2 and py3 relation) , bytes ) to (builtins.str) and logically mapping cannot work in both directions (only in limited cases).

That was exactly my point when I said that " I am even not sure how safe it is to use pickle to pass data between python versions". The problem that you are just describing is one of the arguments in  https://eev.ee/blog/2016/07/31/python-faq-how-do-i-port-to-python-3/#pickle to recommend against pickle.
I just put the futurized version to make the point that the solution proposed by @reszelaz would need to be changed when py2+3 support was attempted.

> So for me if you use pickle you cannot use builtins.str (do we have to?).

I think that the problem is not specific to `builtins.str` (which BTW, I think it is a good idea to use when providing  py2+3 compatibility), but more general, and that is why I think that it may be worth refactoring (possibly with json) to avoid the problem.

**Comment by jkotan** [comment] 2018-11-19 18:54
@cpascual , I think that the patch from @reszelaz is reasonable. In principle you can use  in the same module  `pickles`  and `str` from `builtins` by
```python
from builtins import str as newstr
```
You don't have to override the `str` type. 

In order to make the patch py3 compatible one has only to add
```python
if PY3: 
   unicode = str
```
On the other hand it would be good to support also JSON `Environment` (simultaniuously with pickle) in sardana 3.

**Comment by reszelaz** [comment] 2018-11-20 17:36
@jkotan, both @cpascual and myself or on a course until Friday. We will get back to this issue soon. Sorry for the delay..

**Comment by jkotan** [comment] 2018-11-21 08:01
Currently for me the 1. workaround works quite good so for me it is not argent.  Since, it looks like a solution is not straightforward so anyhow it will take probably more time ;) . No problem.

**Comment by reszelaz** [comment] 2019-09-10 07:51
@jkotan since we moved to Python3 is this still an issue? Thanks!

**Comment by reszelaz** [comment] 2021-01-26 12:08
I will proceed to close this issue. Please reopen if you think we should still do something about it.
Many thanks!

**Closed by reszelaz** 2021-01-26 12:08 UTC
